list = [1,23,43, 34, 75]
print("Original list = ", list) 
print("Slice list[1:-1] = ", list[1:-1])
del list[2]
print("del list[2] = ", list)
list.remove(34)
print("list.remove(34) = ", list)
list.insert(2,55)
print("list.insert(2,55) = ", list)
list.insert(0,99)
print("list.insert(0,99) = ", list)
newlist = [44,64,92]
print("newlist = ", newlist)
list.extend(newlist)
print("list.extend(newlist) = ", list)
list.reverse()
print("list.reverse() = ", list)
list.sort()
print("list.sort() = ", list)
list.sort(reverse=True)
print("list.sort(reverse=True)", list)
string = "This is a list string"
print("string = ", string)
strlist = string.split(" ")
print("strlist = ", strlist)
strlist.sort(key=len)   # list.sort(key=callbleFunction)
print("strlist.sort(key=len) = ", strlist)
strlist.sort(key=len,reverse=True)
print("strlist.sort(key=len,reverse=True) = ", strlist)